concurrent = 8
check_interval = 0

[[runners]]
  name = "Example Docker GitLab Runner"
  limit = 0
  output_limit = 4096
  url = "http://mock:8000"
  environment = []
  id = 0
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    image = ""
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = "if-not-present"
    shm_size = 0
  [runners.feature_flags]
    FF_TIMESTAMPS = true
  [runners.cache]
